### ISSUE TITLE
Request: list output of changed techniques in numerical order

### ISSUE THREAD

**Issue by marco-vdk** [siriussecurity/dettectinator#10]
By doing so, scoring (which stays a manual burden) can be executed much quicker by using the DeTT&CT Editor in combination with the <arrow down> button. Especially in cases when many techniques have been changed one doesn't have to go criss-cross through the yaml file.

**Comment by mveken** [comment]
In the next release results will be sorted when written to the console and the (new) log file.

**Comment by mveken** [comment]
It's been added into release 1.2.0. :)

**Comment by marco-vdk** [comment]
> It's been added into release 1.2.0. :)

Wow, that was quick!! Great! Thnx.
