### ISSUE TITLE
Improve help/wording for unused detection cleaning

### ISSUE THREAD

**Issue by Karneades** [siriussecurity/dettectinator#7]
Hi

Thanks for the awesome addition to DeTT&CT! Really cool library and cli tool!

It was unclear to me based on https://github.com/siriussecurity/dettectinator/wiki/Dettectinator-as-a-CLI-tool#checkclean-unused-detections--ch---check_unused--cl---clean_unused and the `--help` (`optional arguments:`) that I have to provide both, `-ch` and `-cl`, to remove unused detections. I only used the clean-switch and had a hard time figuring out (digging into the source code), to find out that both are needed.

Proposal: Improve wording to clearly state that for removing unused detections one must provide both of these switches.

If I missed reading the right section in the help, then sorry for the trouble ;)

**Comment by Karneades** [comment]
And is it possible to remove techniques somehow after removing all detections from a technique?

**Comment by rubinatorz** [comment]
hi @Karneades 

You're right, your first point was not fully clear on the wiki and in the CLI help. I've made some improvements for this. Thank you!

And regarding your second point, I've added this one to our backlog.
